---
- hosts: web
  tasks:
  - name: Install ntpd
    yum:
      name: ntp 
      state: latest


  - name: Reconfigure time servers
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^server.*iburst$'
      line: 'server pool.ntp.org iburst'
      backup: yes
    notify: restart ntpd
    

  handlers: 
  - name: restart ntpd
    service:
      name: ntpd
      state: restarted
      enabled: yes